baseURL = 'https://llayta.github.io/llayta.github.io/'
languageCode = 'en-us'
title = 'Arduous'
theme = "color-your-world"

[params]
  # Site description
  description = "Layta's blogging website"
  
  # Author
  author      = "Layta"
  authorDesc  = "Website for all my writeups, explanations and meowing!"
  
  footerText = [ "Website for all of my writeups, explanations, and fun stuff" ]  
  
  hasNoscriptNotice = true

  imgPath = "static/avatar.ico"

  [params.search]
    # Enable search form (at the post list)
    # The default value is false
    enable = true
  
    # Limit search results
    # The default value is 30
    maxResults = 15
    
    # Limit seach field input and pattern matching
    minLength = 3   # Default is 3
    maxLength = 32  # Default is 32
    
    # Optional placeholder for search field
    placeholder = "Enter for keywords"
    

  [params.style]
    # Dark mode as default
    # User preferences (site/system settings) will still have priority over it
    # The default is false
    isDark = true

    # Disable the use of system settings (prefers-color-scheme)
    # The default is false
    ignoreSystemSettings = false

    # Accent colors for dark and light mode respectively
    darkAccent   = "#1dbc91" # Default is "#1dbc91"
    lightAccent  = "#1f676b" # Default is "#1f676b"

    # More colors, pick as many as you want (not really sure if there's a limit)
    # Apparently these may not show up on every modern browser (ie. Firefox)
    # There's no default value. Used here just as example
    presets = [ "#225670", "#dd587c", "#902b37", "#f3a530", "#754e85", "#7fc121", "#a8314a", "#ff7433", "#3e6728", "#c063bd", "#805080", "#9d629d", "#a064a0", "#7daa50", "#284531", "#285790", "#F5A83D", "#88aa33", "#015660", "#bf274e", "#bf4242", "#51b37c" ]

    # Use an icon or text for footnote return links
    # The default is false
    hasIconAsFootnoteReturnLink = true
    
    # For the social shortcode
    # Use flexbox (with flex-grow) or grid (equal width)
    # The default is false
    socialIsFlex = false
    
    # Keep anchor links hidden until it's focused/hovered
    # The default is false
    hideAnchors = true
    
    # To make use of the custom Chroma, this should be true
    # and "noClasses" (at markup.highlight) should be false
    # The default is true
    useCustomChroma = true

    # CSS animation transition when changing colors
    # The default is ".5s ease"
    changeTransition = ".3s ease"
    
    
  # For a simple 404
  [params.notFound]
    title         = "Page not found"
    description   = "This page was not found!"
    paragraph     = "Valid paths are: /posts/ and /contacts/!"
    
  [params.social.centralized]
    # entry         = [ "username", "label (optional)" ]
    # The "entry" here IS important. It's used to load the data.
  [params.social.decentralized]    
    
[languages]
  [languages.en]
   
    languageName = "English"
    
    [languages.en.menu]

      [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/"

      [[languages.en.menu.main]]
        name = "Posts"
        weight = 2
        url = "posts/"

      [[languages.en.menu.main]]
        name = "Resources"
        weight = 3
        url = "Resource/"
